"""Pure-Python inspection helpers for .hip scene files."""

from hou_scene_inspector.cpio import CpioEntry, CpioFormatError, read_entries
from hou_scene_inspector.oracle import compare_oracle, load_oracle
from hou_scene_inspector.oracle_matrix import (
    OracleMatrixOptions,
    discover_hip_files,
    format_matrix_report,
    oracle_path_for,
    run_oracle_matrix,
)
from hou_scene_inspector.parsers import (
    Channel,
    ChannelReference,
    ChannelSegment,
    NodeDef,
    NodeFlags,
    NodeInit,
    NodeInput,
    NodeOutput,
    NodeStat,
    ParmTemplate,
    ParmValue,
    Take,
    TakeOverride,
    parse_channels,
    parse_parms,
    parse_order,
    parse_spareparm_templates,
    parse_start,
    parse_takes,
    parse_userdata,
    parse_variables,
)
from hou_scene_inspector.scene import BinaryRecordInfo, Connection, DrivenParmLink, HipFile, Node

__all__ = [
    "Channel",
    "ChannelReference",
    "ChannelSegment",
    "BinaryRecordInfo",
    "Connection",
    "CpioEntry",
    "CpioFormatError",
    "DrivenParmLink",
    "HipFile",
    "Node",
    "NodeDef",
    "NodeFlags",
    "NodeInit",
    "NodeInput",
    "NodeOutput",
    "NodeStat",
    "OracleMatrixOptions",
    "ParmTemplate",
    "ParmValue",
    "Take",
    "TakeOverride",
    "compare_oracle",
    "discover_hip_files",
    "format_matrix_report",
    "load_oracle",
    "oracle_path_for",
    "parse_channels",
    "parse_parms",
    "parse_order",
    "parse_spareparm_templates",
    "parse_start",
    "parse_takes",
    "parse_userdata",
    "parse_variables",
    "read_entries",
    "run_oracle_matrix",
]
